###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Learning Backend",
    "author": "swati saxena",
    "url": "swati.s@gmail.com",
    "likes": 19
}

###
GET http://localhost:3003/api/blogs/60d0d19b77900af38a55f787

###
DELETE http://localhost:3003/api/blogs/60d0d1e077900af38a55f788

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"sushi",
    "name":"sushmita",
    "password":"987654321"
}